version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: video-player:latest
    container_name: video-player
    ports:
      - "7978:7978"
    volumes:
      - ./backend/config:/app/config
      - /d/videos:/videos
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped