FROM node:18-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm install --production

COPY backend/ .

RUN mkdir -p config

EXPOSE 7978

VOLUME ["/app/config", "/videos"]

CMD ["node", "app.js"]